services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=apiblog'
      - 'MYSQL_ROOT_PASSWORD=102938'
      - 'MYSQL_USER=domino123'
      - 'MYSQL_PASSWORD=domino123'
    ports:
      - '3307:3306'