
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=apiblog
      - MYSQL_ROOT_PASSWORD=102938
      - MYSQL_USER=domino123
      - MYSQL_PASSWORD=domino123
    ports:
      - '3307:3306'
    networks:
      - blog-network
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: C:/Users/USUARIO/Documents/VscProjects/FrontEndApiBlog/frontApiBlog
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    networks:
      - blog-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    networks:
      - blog-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/apiblog
      SPRING_DATASOURCE_USERNAME: domino123
      SPRING_DATASOURCE_PASSWORD: domino123
      SPRING_REDIS_URL: rediss://default:AZxAAAIncDI5YzY0NTU3NTc0Zjc0MmVkODc1OWIzMjBiYzlhMzgwMnAyNDAwMDA@major-mastodon-40000.upstash.io:6379


networks:
  blog-network:
    driver: bridge

volumes:
  mysql_data:

