services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=apiblog'
      - 'MYSQL_ROOT_PASSWORD=102938'
      - 'MYSQL_USER=domino123'
      - 'MYSQL_PASSWORD=domino123'
    ports:
      - '3307:3306'
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: [ "start-dev", "--http-port=9090", "-d"]
    ports:
      - '9090:9090'